spring.application.name=helpdesk

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-twilight-lake-a00xga11-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pLBVMlu1C9Tg

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=${PORT:8080}
